Add breaking improvements page
onflow/cadence-lang.org pull request #86
Opened 2024-04-16 15:33 UTC by jribbink

2024-04-19 19:31 UTC, gregsantos requested changes

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +View functions allow developers to improve the reliability and safety of their programs, and helps them to reason about the effects of their and the programs of others.
```suggestion
View functions enable developers to enhance the reliability and safety of their programs, facilitating a clearer understanding of the impacts of their own code and that of others.
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +However, we believe that the pain is worth it, given the significant improvements that make Cadence development significantly more powerful and pleasant, and enabling developers to for write and depl
```suggestion
We fully recognize the frustration developers feel when updates break their code, necessitating revisions. Nonetheless, we are convinced that this inconvenience is justified by the substantial enhancements to Cadence development. These improvements not only make development more effective and enjoyable but also empower developers to write and deploy immutable contracts.
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +This improvement was proposed in [FLIP 1056 7](https://github.com/onflow/flips/blob/main/cadence/20220715-cadence-purity-analysis.md). To learn more, please consult the FLIP and documentation.
```suggestion
This improvement was proposed in [FLIP 1056](https://github.com/onflow/flips/blob/main/cadence/20220715-cadence-purity-analysis.md). To learn more, please consult the FLIP and documentation.
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +<summary>Naming Rules Got Tightened</summary>
```suggestion
<summary>Tightening Of Naming Rules</summary>
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +<summary>`pub` and `priv` Access Modifiers Got Removed</summary>
```suggestion
<summary>Removal of `pub` and `priv` Access Modifiers</summary>
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +Access control is now handled using a new feature called Entitlements, as originally proposed across [\*\*FLIP 54 3](https://github.com/onflow/flips/blob/main/cadence/20221214-auth-remodel.md)** and 
```suggestion
Access control is now handled using a new feature called Entitlements, as originally proposed across **[FLIP 543](https://github.com/onflow/flips/blob/main/cadence/20221214-auth-remodel.md)** and **[FLIP 943](https://github.com/onflow/flips/blob/main/cadence/20230623-entitlement-improvements.md)**.
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +<summary>Restricted Types Got Replaced with Intersection Types</summary>
```suggestion
<summary>Replacement of Restricted Types with Intersection Types</summary>
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +The `pub`, `priv` and `pub(set)` access modifiers got removed from the language, in favor of their more explicit `access(all)` and `access(self)` equivalents (for `pub` and `priv`, respectively).
```suggestion
The `pub`, `priv` and `pub(set)` access modifiers are being removed from the language, in favor of their more explicit `access(all)` and `access(self)` equivalents (for `pub` and `priv`, respectively).
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +<summary>External Mutation Got Improved</summary>
```suggestion
<summary>External Mutation Improvement</summary>
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +<summary>Nested Type Requirements Got Removed</summary>
```suggestion
<summary>Removal Of Nested Type Requirements</summary>
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +<summary>Interface Inheritance added</summary>
```suggestion
<summary>Interface Inheritance Added</summary>
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +#### ℹ️ Description and ✨ example
```suggestion
#### ℹ️ Description and ✨ Example
```

2024-04-19 19:31 UTC, gregsantos commented on versioned_docs/version-1.0/cadence-migration-guide/breaking-improvements.md
> +<summary>Incorrect Operators in Reference Expressions Get Reported</summary>
```suggestion
<summary>Incorrect Operators In Reference Expressions Get Reported</summary>
```

2024-04-19 20:32 UTC, Aliserag commented
Some nits @jribbink https://www.loom.com/share/caba14407c62436193b9677a34f73e73?sid=a0c519c7-f18d-4d37-ad54-b62f1159b790

2024-04-26 19:02 UTC, gregsantos approved these changes
Great!

2024-04-26 22:53 UTC, merged